name: catechism
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>3.0.0'

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  collection: ^1.17.2
  dio: ^5.2.1+1
  dotenv: ^4.1.0
  http: ^1.1.0
  pdf: ^3.10.4
  pretty_dio_logger: ^1.3.1
